// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: album_lists.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAlbumList = `-- name: CreateAlbumList :one
insert into album_lists (id, created_at, updated_at, user_id, title)
values (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2
)
returning id, created_at, updated_at, user_id, title
`

type CreateAlbumListParams struct {
	UserID uuid.UUID
	Title  sql.NullString
}

func (q *Queries) CreateAlbumList(ctx context.Context, arg CreateAlbumListParams) (AlbumList, error) {
	row := q.db.QueryRowContext(ctx, createAlbumList, arg.UserID, arg.Title)
	var i AlbumList
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
	)
	return i, err
}

const createAlbumList_relKey = `-- name: CreateAlbumList_relKey :one
insert into album_lists_relKey (id, album_lists_id,album_id)
values (
	gen_random_uuid(),
	$1,
	$2
)
returning id, album_lists_id, album_id
`

type CreateAlbumList_relKeyParams struct {
	AlbumListsID uuid.UUID
	AlbumID      uuid.UUID
}

func (q *Queries) CreateAlbumList_relKey(ctx context.Context, arg CreateAlbumList_relKeyParams) (AlbumListsRelkey, error) {
	row := q.db.QueryRowContext(ctx, createAlbumList_relKey, arg.AlbumListsID, arg.AlbumID)
	var i AlbumListsRelkey
	err := row.Scan(&i.ID, &i.AlbumListsID, &i.AlbumID)
	return i, err
}

const getAlbumsFromList = `-- name: GetAlbumsFromList :many
SELECT albums.id, albums.name, albums.img_url
FROM album_lists
JOIN album_lists_relKey ON album_lists.id = album_lists_relKey.album_lists_id
JOIN albums ON albums.id = album_lists_relKey.album_id
WHERE album_lists.user_id = $1
`

type GetAlbumsFromListRow struct {
	ID     uuid.UUID
	Name   string
	ImgUrl string
}

func (q *Queries) GetAlbumsFromList(ctx context.Context, userID uuid.UUID) ([]GetAlbumsFromListRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumsFromList, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumsFromListRow
	for rows.Next() {
		var i GetAlbumsFromListRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ImgUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLists = `-- name: GetUserLists :many
SELECT list.id, list.title
FROM album_lists as list
WHERE list.user_id = $1
`

type GetUserListsRow struct {
	ID    uuid.UUID
	Title sql.NullString
}

func (q *Queries) GetUserLists(ctx context.Context, userID uuid.UUID) ([]GetUserListsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserListsRow
	for rows.Next() {
		var i GetUserListsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
