// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Genre     string
	ImgUrl    string
	ArtistID  uuid.UUID
}

type AlbumList struct {
	ID          uuid.UUID
	UserListsID uuid.UUID
	AlbumID     uuid.UUID
}

type AlbumReview struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	AlbumID   uuid.UUID
	Title     sql.NullString
	Review    sql.NullString
	Score     string
}

type Artist struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FormedAt  string
	Name      string
	Biography sql.NullString
	Genre     string
	ImgUrl    string
}

type ArtistFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ArtistID  uuid.UUID
}

type Track struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	Duration         int32
	AlbumTrackNumber int32
	ArtistID         uuid.UUID
	AlbumID          uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	ImgUrl         string
	HashedPassword string
	IsAdmin        bool
}

type UserList struct {
	IDPlaylistA uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        sql.NullString
	Description sql.NullString
	Type        sql.NullString
	UserID      uuid.UUID
}
