// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Artist struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FormedAt  string
	Name      string
	Biography sql.NullString
	Genre     string
	ImgUrl    string
}

type ArtistFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ArtistID  uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ImgUrl    string
}
