// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tracks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAlbumTracks = `-- name: CreateAlbumTracks :one
insert into tracks (id, created_at, updated_at, name, duration, album_track_number, artist_id, album_id)
values (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2,
	$3,
	$4,
	$5
)
returning id, created_at, updated_at, name, duration, album_track_number, artist_id, album_id
`

type CreateAlbumTracksParams struct {
	Name             string
	Duration         int32
	AlbumTrackNumber int32
	ArtistID         uuid.UUID
	AlbumID          uuid.UUID
}

func (q *Queries) CreateAlbumTracks(ctx context.Context, arg CreateAlbumTracksParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createAlbumTracks,
		arg.Name,
		arg.Duration,
		arg.AlbumTrackNumber,
		arg.ArtistID,
		arg.AlbumID,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Duration,
		&i.AlbumTrackNumber,
		&i.ArtistID,
		&i.AlbumID,
	)
	return i, err
}

const getTop12Tracks = `-- name: GetTop12Tracks :many
select distinct on (albums.name)
	tracks.id, tracks.name, tracks.duration,
	albums.name as album_name, albums.img_url as img_url,
	artists.name as artist_name
from tracks
join albums on albums.id = tracks.album_id
join artists on artists.id = albums.artist_id
limit 12
`

type GetTop12TracksRow struct {
	ID         uuid.UUID
	Name       string
	Duration   int32
	AlbumName  string
	ImgUrl     string
	ArtistName string
}

func (q *Queries) GetTop12Tracks(ctx context.Context) ([]GetTop12TracksRow, error) {
	rows, err := q.db.QueryContext(ctx, getTop12Tracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTop12TracksRow
	for rows.Next() {
		var i GetTop12TracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Duration,
			&i.AlbumName,
			&i.ImgUrl,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrack = `-- name: GetTrack :one
select tracks.id, tracks.created_at, tracks.updated_at, tracks.name, tracks.duration, tracks.album_track_number, tracks.artist_id, tracks.album_id, albums.img_url
from tracks
join albums on albums.id = tracks.album_id
where tracks.id = $1
`

type GetTrackRow struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	Duration         int32
	AlbumTrackNumber int32
	ArtistID         uuid.UUID
	AlbumID          uuid.UUID
	ImgUrl           string
}

func (q *Queries) GetTrack(ctx context.Context, id uuid.UUID) (GetTrackRow, error) {
	row := q.db.QueryRowContext(ctx, getTrack, id)
	var i GetTrackRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Duration,
		&i.AlbumTrackNumber,
		&i.ArtistID,
		&i.AlbumID,
		&i.ImgUrl,
	)
	return i, err
}
